version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_pass
    volumes:
      - mongodb_data:/data/db

  api:
    image: cassianodev/greencycle-api:latest
    ports:
      - "8080:8080"
    environment:
      - PROFILE=dev
      - SPRING_DATA_MONGODB_URI=mongodb://root:root_pass@mongo:27017/greencycle?authSource=admin
    depends_on:
      mongodb:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s

  tests:
    image: maven:3.9.8-eclipse-temurin-21
    container_name: test-runner
    working_dir: /opt/tests
    volumes:
      - .:/opt/tests
    depends_on:
      api:
        condition: service_healthy
    entrypoint: ["sh", "-c", "sleep 20 && mvn clean test"]

volumes:
  mongodb_data:
    driver: local
