name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - '*'  # Qualquer branch

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Última versão estável
          distribution: 'adopt'

      - name: Build Docker image
        run: docker build -t greencycle-api:latest .

      - name: Start Docker Compose
        run: docker-compose up -d  # Inicia o container em background

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        env:
          API_BASE_URL: http://localhost:8080
        run: mvn clean test

      - name: Stop Docker Compose
        run: docker-compose down  # Para e remove os containers após os testes

  deploy:
    runs-on: ubuntu-latest
    needs: continuous-integration
    if: success()
    steps:
      - name: Deploy application
        run: |
          echo "Deploying application..."
          # Adicione aqui seu comando de deploy
