name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start API with Docker Compose
        run: |
          docker-compose -f ../greencycle/docker-compose.yml up -d
        env:
          API_BASE_URL: "http://localhost:8080"

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build and run tests
        run: mvn clean test
        env:
          API_BASE_URL: "http://localhost:8080"

      - name: Clean up
        if: always()
        run: docker-compose -f ../greencycle/docker-compose.yml down --volumes
