name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u seu_usuario --password-stdin

      - name: Build and run tests with Docker Compose
        run: |
          docker-compose up --build --abort-on-container-exit

      - name: Clean up
        if: always()
        run: docker-compose down --volumes
